### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by hhimanshu** [plaid/pattern-transfers#33]
Hello, I have followed all steps as outlined in the README file.

When I click on "Pay first month with bank account", I get the following error on console

```
{
    "message": "Request failed with status code 400",
    "name": "Error",
    "stack": "Error: Request failed with status code 400\n    at createError (/opt/server/node_modules/plaid/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/opt/server/node_modules/plaid/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/opt/server/node_modules/plaid/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:538:35)\n    at endReadableNT (node:internal/streams/readable:1345:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
    "config": {
        "url": "https://sandbox.plaid.com/transfer/intent/create",
        "method": "post",
        "data": "{\"mode\":\"PAYMENT\",\"amount\":\"100.00\",\"ach_class\":\"ppd\",\"description\":\"payment\",\"user\":{\"legal_name\":\"Harit Himanshu\"}}",
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json",
            "User-Agent": "Plaid Node v10.5.0",
            "Plaid-Version": "2020-09-14",
            "PLAID-CLIENT-ID": "62a2269b92894d0012b1f3a5",
            "PLAID-SECRET": "",
            "Content-Length": 117
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        }
    }
}
```

The `make logs` are clean
```
pattern-transfers-client-1  | Why you should do it regularly:
pattern-transfers-client-1  | https://github.com/browserslist/browserslist#browsers-data-updating
pattern-transfers-client-1  | Compiled successfully!
pattern-transfers-client-1  | 
pattern-transfers-client-1  | You can now view client in the browser.
pattern-transfers-client-1  | 
pattern-transfers-client-1  |   Local:            http://localhost:3002
pattern-transfers-client-1  |   On Your Network:  http://172.24.0.4:3002
pattern-transfers-client-1  | 
pattern-transfers-client-1  | Note that the development build is not optimized.
pattern-transfers-client-1  | To create a production build, use npm run build.
pattern-transfers-client-1  | 
```

I have `transfer` product enabled and I am able to make API calls with Postman. Please help
```

**Comment by phoenixy1** [comment]
@hhimanshu If you check out the logs section of the dashboard at https://dashboard.plaid.com/activity/logs and click through there should be an error code that you can look up in the docs search bar to find out more about why the call failed -- do you see an error code there?

**Comment by phoenixy1** [comment]
@hhimanshu just to follow up, I checked with the team and discovered that there was a misconfiguration in which some new accounts were not being given access to the transfer UI product by default, even if they did have access to transfer, which could cause the problem you're seeing. We've since fixed the misconfiguration, so let me know if that solves the issue for you (and if not, let me know the error code you're hitting!)

**Comment by hhimanshu** [comment]
@phoenixy1 , it worked for me now. 
<img width="994" alt="image" src="https://user-images.githubusercontent.com/6589036/205383919-9cfe3fc7-177d-42ed-b3f4-88ab1cc07fd7.png">

Not sure what was the issue. But one more thing that I had to do was to move the `SECRET` from `DEVELOPMENT` to `SANDBOX`. That means, fill secret value in
```
PLAID_SECRET_SANDBOX=*******************************
```

instead of 
```
PLAID_SECRET_DEVELOPMENT=
```

I appreciate your help!
